add 'm4' to Brewfile
Without this I get:

    ==> CMD: ./autogen.sh
    Checking whether you have the necessary tools...
    (Read INSTALL.REPO for more details on building Emacs)
    Checking for autoconf (need at least version 2.65) ... ok
    Your system has the required tools.
    Building aclocal.m4 ...
    Running 'autoreconf -fi -I m4' ...
    autom4te: need GNU m4 1.4 or later: /usr/bin/m4
    autom4te: need GNU m4 1.4 or later: /usr/bin/m4
    autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
    ERROR: Exit code: 1